---
title: "Turgor: series temporales"
author: "M. Abel Herrera"
format: html
editor: visual
execute:
  echo: false
  warning: false
  message: false
filters:
  - lightbox
lang: es
---

```{r}
source('C:/Hemera/garces/script/funciones/paquetes.R')
data_turgor <- read_rds('C:/Hemera/garces/data/data_processed/turgor.rds')
```

## Temporada 2022-2023

::: panel-tabset
# Septiembre

```{r}
#| fig-width: 10
#| fig-height: 7
#| fig-align: center
#| lightbox: true

data_turgor |>
  mutate(fecha_hora = fecha_hora_f(fecha,hora)) |>
  filter(temporada == '2022-2023',
         month(fecha) == 9) |>
  pivot_longer(cols = c('turgor','turgor_filtrado'),names_to = 'tipo',values_to = 'turgor') |>
  ggplot(aes(fecha_hora,turgor,color=tipo)) +
  geom_point(size = .5) +
  facet_grid(tratamiento+unidad~sitio, labeller = as_labeller(names)) +
  scale_color_hue(labels = c("Original", "Filtrado")) +
  labs(y = expression("P"[p]),
       x = 'Fecha',
       color = 'Turgor') +
  guides(color = guide_legend(override.aes = list(size = 3)))
```

# Octubre

```{r}
#| fig-width: 10
#| fig-height: 7
#| fig-align: center
#| lightbox: true

data_turgor |>
  mutate(fecha_hora = fecha_hora_f(fecha,hora)) |>
  filter(temporada == '2022-2023',
         month(fecha) == 10) |>
  pivot_longer(cols = c('turgor','turgor_filtrado'),names_to = 'tipo',values_to = 'turgor') |>
  ggplot(aes(fecha_hora,turgor,color=tipo)) +
  geom_point(size = .5) +
  facet_grid(tratamiento+unidad~sitio, labeller = as_labeller(names)) +
  scale_color_hue(labels = c("Original", "Filtrado")) +
  labs(y = expression("P"[p]),
       x = 'Fecha',
       color = 'Turgor') +
  guides(color = guide_legend(override.aes = list(size = 3)))
```

# Noviembre

```{r}
#| fig-width: 10
#| fig-height: 7
#| fig-align: center
#| lightbox: true

data_turgor |>
  mutate(fecha_hora = fecha_hora_f(fecha,hora)) |>
  filter(temporada == '2022-2023',
         month(fecha) == 11) |>
  pivot_longer(cols = c('turgor','turgor_filtrado'),names_to = 'tipo',values_to = 'turgor') |>
  ggplot(aes(fecha_hora,turgor,color=tipo)) +
  geom_point(size = .5) +
  facet_grid(tratamiento+unidad~sitio, labeller = as_labeller(names)) +
  scale_color_hue(labels = c("Original", "Filtrado")) +
  labs(y = expression("P"[p]),
       x = 'Fecha',
       color = 'Turgor') +
  guides(color = guide_legend(override.aes = list(size = 3)))
```

# Diciembre

```{r}
#| fig-width: 10
#| fig-height: 7
#| fig-align: center
#| lightbox: true

data_turgor |>
  mutate(fecha_hora = fecha_hora_f(fecha,hora)) |>
  filter(temporada == '2022-2023',
         month(fecha) == 12) |>
  pivot_longer(cols = c('turgor','turgor_filtrado'),names_to = 'tipo',values_to = 'turgor') |>
  ggplot(aes(fecha_hora,turgor,color=tipo)) +
  geom_point(size = .5) +
  facet_grid(tratamiento+unidad~sitio, labeller = as_labeller(names)) +
  scale_color_hue(labels = c("Original", "Filtrado")) +
  labs(y = expression("P"[p]),
       x = 'Fecha',
       color = 'Turgor') +
  guides(color = guide_legend(override.aes = list(size = 3)))
```

# Enero

```{r}
#| fig-width: 10
#| fig-height: 7
#| fig-align: center
#| lightbox: true

data_turgor |>
  mutate(fecha_hora = fecha_hora_f(fecha,hora)) |>
  filter(temporada == '2022-2023',
         month(fecha) == 1) |>
  pivot_longer(cols = c('turgor','turgor_filtrado'),names_to = 'tipo',values_to = 'turgor') |>
  ggplot(aes(fecha_hora,turgor,color=tipo)) +
  geom_point(size = .5) +
  facet_grid(tratamiento+unidad~sitio, labeller = as_labeller(names)) +
  scale_color_hue(labels = c("Original", "Filtrado")) +
  labs(y = expression("P"[p]),
       x = 'Fecha',
       color = 'Turgor') +
  guides(color = guide_legend(override.aes = list(size = 3)))
```

# Febrero

```{r}
#| fig-width: 10
#| fig-height: 7
#| fig-align: center
#| lightbox: true

data_turgor |>
  mutate(fecha_hora = fecha_hora_f(fecha,hora)) |>
  filter(temporada == '2022-2023',
         month(fecha) == 2) |>
  pivot_longer(cols = c('turgor','turgor_filtrado'),names_to = 'tipo',values_to = 'turgor') |>
  ggplot(aes(fecha_hora,turgor,color=tipo)) +
  geom_point(size = .5) +
  facet_grid(tratamiento+unidad~sitio, labeller = as_labeller(names)) +
  scale_color_hue(labels = c("Original", "Filtrado")) +
  labs(y = expression("P"[p]),
       x = 'Fecha',
       color = 'Turgor') +
  guides(color = guide_legend(override.aes = list(size = 3)))
```

# Marzo

```{r}
#| fig-width: 10
#| fig-height: 7
#| fig-align: center
#| lightbox: true

data_turgor |>
  mutate(fecha_hora = fecha_hora_f(fecha,hora)) |>
  filter(temporada == '2022-2023',
         month(fecha) == 3) |>
  pivot_longer(cols = c('turgor','turgor_filtrado'),names_to = 'tipo',values_to = 'turgor') |>
  ggplot(aes(fecha_hora,turgor,color=tipo)) +
  geom_point(size = .5) +
  facet_grid(tratamiento+unidad~sitio, labeller = as_labeller(names)) +
  scale_color_hue(labels = c("Original", "Filtrado")) +
  labs(y = expression("P"[p]),
       x = 'Fecha',
       color = 'Turgor') +
  guides(color = guide_legend(override.aes = list(size = 3)))
```

# Abril

```{r}
#| fig-width: 10
#| fig-height: 7
#| fig-align: center
#| lightbox: true

data_turgor |>
  mutate(fecha_hora = fecha_hora_f(fecha,hora)) |>
  filter(temporada == '2022-2023',
         month(fecha) == 4) |>
  pivot_longer(cols = c('turgor','turgor_filtrado'),names_to = 'tipo',values_to = 'turgor') |>
  ggplot(aes(fecha_hora,turgor,color=tipo)) +
  geom_point(size = .5) +
  facet_grid(tratamiento+unidad~sitio, labeller = as_labeller(names)) +
  scale_color_hue(labels = c("Original", "Filtrado")) +
  labs(y = expression("P"[p]),
       x = 'Fecha',
       color = 'Turgor') +
  guides(color = guide_legend(override.aes = list(size = 3)))
```

# Mayo

```{r}
#| fig-width: 10
#| fig-height: 7
#| fig-align: center
#| lightbox: true

data_turgor |>
  mutate(fecha_hora = fecha_hora_f(fecha,hora)) |>
  filter(temporada == '2022-2023',
         month(fecha) == 5) |>
  pivot_longer(cols = c('turgor','turgor_filtrado'),names_to = 'tipo',values_to = 'turgor') |>
  ggplot(aes(fecha_hora,turgor,color=tipo)) +
  geom_point(size = .5) +
  facet_grid(tratamiento+unidad~sitio, labeller = as_labeller(names)) +
  scale_color_hue(labels = c("Original", "Filtrado")) +
  labs(y = expression("P"[p]),
       x = 'Fecha',
       color = 'Turgor') +
  guides(color = guide_legend(override.aes = list(size = 3)))
```
:::

## Temporada 2023-2024

::: panel-tabset
# Septiembre

```{r}
#| fig-width: 10
#| fig-height: 7
#| fig-align: center
#| lightbox: true

data_turgor |>
  mutate(fecha_hora = fecha_hora_f(fecha,hora)) |>
  filter(temporada == '2023-2024',
         month(fecha) == 9) |>
  pivot_longer(cols = c('turgor','turgor_filtrado'),names_to = 'tipo',values_to = 'turgor') |>
  ggplot(aes(fecha_hora,turgor,color=tipo)) +
  geom_point(size = .5) +
  facet_grid(tratamiento+unidad~sitio, labeller = as_labeller(names)) +
  scale_color_hue(labels = c("Original", "Filtrado")) +
  labs(y = expression("P"[p]),
       x = 'Fecha',
       color = 'Turgor') +
  guides(color = guide_legend(override.aes = list(size = 3)))
```

# Octubre

```{r}
#| fig-width: 10
#| fig-height: 7
#| fig-align: center
#| lightbox: true

data_turgor |>
  mutate(fecha_hora = fecha_hora_f(fecha,hora)) |>
  filter(temporada == '2023-2024',
         month(fecha) == 10) |>
  pivot_longer(cols = c('turgor','turgor_filtrado'),names_to = 'tipo',values_to = 'turgor') |>
  ggplot(aes(fecha_hora,turgor,color=tipo)) +
  geom_point(size = .5) +
  facet_grid(tratamiento+unidad~sitio, labeller = as_labeller(names)) +
  scale_color_hue(labels = c("Original", "Filtrado")) +
  labs(y = expression("P"[p]),
       x = 'Fecha',
       color = 'Turgor') +
  guides(color = guide_legend(override.aes = list(size = 3)))
```

# Noviembre

```{r}
#| fig-width: 10
#| fig-height: 7
#| fig-align: center
#| lightbox: true

data_turgor |>
  mutate(fecha_hora = fecha_hora_f(fecha,hora)) |>
  filter(temporada == '2023-2024',
         month(fecha) == 11) |>
  pivot_longer(cols = c('turgor','turgor_filtrado'),names_to = 'tipo',values_to = 'turgor') |>
  ggplot(aes(fecha_hora,turgor,color=tipo)) +
  geom_point(size = .5) +
  facet_grid(tratamiento+unidad~sitio, labeller = as_labeller(names)) +
  scale_color_hue(labels = c("Original", "Filtrado")) +
  labs(y = expression("P"[p]),
       x = 'Fecha',
       color = 'Turgor') +
  guides(color = guide_legend(override.aes = list(size = 3)))
```

# Diciembre

```{r}
#| fig-width: 10
#| fig-height: 7
#| fig-align: center
#| lightbox: true

data_turgor |>
  mutate(fecha_hora = fecha_hora_f(fecha,hora)) |>
  filter(temporada == '2023-2024',
         month(fecha) == 12) |>
  pivot_longer(cols = c('turgor','turgor_filtrado'),names_to = 'tipo',values_to = 'turgor') |>
  ggplot(aes(fecha_hora,turgor,color=tipo)) +
  geom_point(size = .5) +
  facet_grid(tratamiento+unidad~sitio, labeller = as_labeller(names)) +
  scale_color_hue(labels = c("Original", "Filtrado")) +
  labs(y = expression("P"[p]),
       x = 'Fecha',
       color = 'Turgor') +
  guides(color = guide_legend(override.aes = list(size = 3)))
```

# Enero

```{r}
#| fig-width: 10
#| fig-height: 7
#| fig-align: center
#| lightbox: true

data_turgor |>
  mutate(fecha_hora = fecha_hora_f(fecha,hora)) |>
  filter(temporada == '2023-2024',
         month(fecha) == 1) |>
  pivot_longer(cols = c('turgor','turgor_filtrado'),names_to = 'tipo',values_to = 'turgor') |>
  ggplot(aes(fecha_hora,turgor,color=tipo)) +
  geom_point(size = .5) +
  facet_grid(tratamiento+unidad~sitio, labeller = as_labeller(names)) +
  scale_color_hue(labels = c("Original", "Filtrado")) +
  labs(y = expression("P"[p]),
       x = 'Fecha',
       color = 'Turgor') +
  guides(color = guide_legend(override.aes = list(size = 3)))
```

# Febrero

```{r}
#| fig-width: 10
#| fig-height: 7
#| fig-align: center
#| lightbox: true

data_turgor |>
  mutate(fecha_hora = fecha_hora_f(fecha,hora)) |>
  filter(temporada == '2023-2024',
         month(fecha) == 2) |>
  pivot_longer(cols = c('turgor','turgor_filtrado'),names_to = 'tipo',values_to = 'turgor') |>
  ggplot(aes(fecha_hora,turgor,color=tipo)) +
  geom_point(size = .5) +
  facet_grid(tratamiento+unidad~sitio, labeller = as_labeller(names)) +
  scale_color_hue(labels = c("Original", "Filtrado")) +
  labs(y = expression("P"[p]),
       x = 'Fecha',
       color = 'Turgor') +
  guides(color = guide_legend(override.aes = list(size = 3)))
```

# Marzo

```{r}
#| fig-width: 10
#| fig-height: 7
#| fig-align: center
#| lightbox: true

data_turgor |>
  mutate(fecha_hora = fecha_hora_f(fecha,hora)) |>
  filter(temporada == '2023-2024',
         month(fecha) == 3) |>
  pivot_longer(cols = c('turgor','turgor_filtrado'),names_to = 'tipo',values_to = 'turgor') |>
  ggplot(aes(fecha_hora,turgor,color=tipo)) +
  geom_point(size = .5) +
  facet_grid(tratamiento+unidad~sitio, labeller = as_labeller(names)) +
  scale_color_hue(labels = c("Original", "Filtrado")) +
  labs(y = expression("P"[p]),
       x = 'Fecha',
       color = 'Turgor') +
  guides(color = guide_legend(override.aes = list(size = 3)))
```

# Abril

```{r}
#| fig-width: 10
#| fig-height: 7
#| fig-align: center
#| lightbox: true

data_turgor |>
  mutate(fecha_hora = fecha_hora_f(fecha,hora)) |>
  filter(temporada == '2023-2024',
         month(fecha) == 4) |>
  pivot_longer(cols = c('turgor','turgor_filtrado'),names_to = 'tipo',values_to = 'turgor') |>
  ggplot(aes(fecha_hora,turgor,color=tipo)) +
  geom_point(size = .5) +
  facet_grid(tratamiento+unidad~sitio, labeller = as_labeller(names)) +
  scale_color_hue(labels = c("Original", "Filtrado")) +
  labs(y = expression("P"[p]),
       x = 'Fecha',
       color = 'Turgor') +
  guides(color = guide_legend(override.aes = list(size = 3)))
```

:::
