project:
  type: book

book:
  title: "Reporte Proyecto ID23|10297"
  author: "M. Abel Herrera"
  date: "4/3/2024"
  chapters:
    - index.qmd
    - part: 'Capítulo 1: Análisis Explotatorio'
      chapters:
        - intro_cap_1.qmd
        - produccion.qmd
        - calidad.qmd
    - part: 'Capítulo 2: Análisis Comparativo'

bibliography: references.bib

filters:
  - lightbox

format:
  html:
    theme: cosmo
    mermaid: 
        theme: neutral
  pdf:
    documentclass: scrreprt
execute:
  echo: false
  warning: false
  message: false

editor: visual
number-depth: 4
lang: es

