project:
  type: book

book:
  title: "Reporte Proyecto ID23|10297"
  author: "M. Abel Herrera"
  date: "4/3/2024"
  chapters:
    - index.qmd
    - part: capitulo_1.qmd
      chapters:
        - produccion.qmd
        - calidad.qmd
        - parametros_fisio.qmd
        - humedad_suelo.qmd
        - clima.qmd
        - pv.qmd
    - part: capitulo_2.qmd
      chapters: 
        - clustering.qmd
        - limpieza.qmd
        - estandarizacion.qmd
        - turgor_preproc.qmd
    - part: 'Capítulo 3: Análisis Comparativo'

bibliography: references.bib

filters:
  - lightbox

format:
  html:
    theme: cosmo
    mermaid: 
        theme: neutral
  pdf:
    documentclass: scrreprt
execute:
  echo: false
  warning: false
  message: false

editor: visual
number-depth: 4
lang: es

